export const COUNTRY_LIST = [
  { name: 'India', code: 'IN', currency: 'INR', currency_icon: '₹', id: 91, status: 1 },
];

export const STATE_LIST = [
  { country_id: 91, id: 1, name: 'Andaman and Nicobar Islands', code: 'AN', status: 0 },
  { country_id: 91, id: 2, name: 'Andhra Pradesh', code: 'AP', status: 0 },
  { country_id: 91, id: 3, name: 'Arunachal Pradesh', code: 'AR', status: 0 },
  { country_id: 91, id: 4, name: 'Assam', code: 'AS', status: 0 },
  { country_id: 91, id: 5, name: 'Bihar', code: 'BR', status: 0 },
  { country_id: 91, id: 6, name: 'Chandigarh', code: 'CH', status: 0 },
  { country_id: 91, id: 7, name: 'Chhattisgarh', code: 'CG', status: 0 },
  { country_id: 91, id: 8, name: 'Dadra and Nagar Haveli', code: 'DN', status: 0 },
  { country_id: 91, id: 37, name: 'Daman and Diu', code: 'DD', status: 0 },
  { country_id: 91, id: 9, name: 'Delhi', code: 'DL', status: 0 },
  { country_id: 91, id: 10, name: 'Goa', code: 'GA', status: 0 },
  { country_id: 91, id: 11, name: 'Gujarat', code: 'GJ', status: 1 },
  { country_id: 91, id: 12, name: 'Haryana', code: 'HR', status: 0 },
  { country_id: 91, id: 13, name: 'Himachal Pradesh', code: 'HP', status: 0 },
  { country_id: 91, id: 14, name: 'Jammu and Kashmir', code: 'JK', status: 0 },
  { country_id: 91, id: 15, name: 'Jharkhand', code: 'JH', status: 0 },
  { country_id: 91, id: 16, name: 'Karnataka', code: 'KA', status: 0 },
  { country_id: 91, id: 17, name: 'Kerala', code: 'KL', status: 0 },
  { country_id: 91, id: 18, name: 'Lakshadweep', code: 'LD', status: 0 },
  { country_id: 91, id: 19, name: 'Madhya Pradesh', code: 'MP', status: 1 },
  { country_id: 91, id: 20, name: 'Maharashtra', code: 'MH', status: 1 },
  { country_id: 91, id: 21, name: 'Manipur', code: 'MN', status: 0 },
  { country_id: 91, id: 22, name: 'Meghalaya', code: 'ML', status: 0 },
  { country_id: 91, id: 23, name: 'Mizoram', code: 'MZ', status: 0 },
  { country_id: 91, id: 24, name: 'Nagaland', code: 'NL', status: 0 },
  { country_id: 91, id: 25, name: 'Odisha', code: 'OR', status: 0 },
  { country_id: 91, id: 26, name: 'Puducherry', code: 'PY', status: 0 },
  { country_id: 91, id: 27, name: 'Punjab', code: 'PB', status: 0 },
  { country_id: 91, id: 28, name: 'Rajasthan', code: 'RJ', status: 1 },
  { country_id: 91, id: 29, name: 'Sikkim', code: 'SK', status: 0 },
  { country_id: 91, id: 30, name: 'Tamil Nadu', code: 'TN', status: 0 },
  { country_id: 91, id: 31, name: 'Telangana', code: 'TS', status: 0 },
  { country_id: 91, id: 32, name: 'Tripura', code: 'TR', status: 0 },
  { country_id: 91, id: 33, name: 'Uttar Pradesh', code: 'UP', status: 0 },
  { country_id: 91, id: 34, name: 'Uttarakhand', code: 'UK', status: 0 },
  { country_id: 91, id: 35, name: 'West Bengal', code: 'WB', status: 0 },
];